# Generated by Django 4.2.3 on 2023-07-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vagas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empresa", models.CharField(max_length=100)),
                ("titulo", models.CharField(max_length=150)),
                ("salario", models.CharField(max_length=50)),
                ("escolaridade", models.CharField(max_length=50)),
            ],
        ),
    ]
