# Generated by Django 4.2.3 on 2023-07-28 23:53
# pylint: disable=C0103
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_alter_candidatura_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidatura",
            name="pontuacao",
            field=models.IntegerField(default=0),
        ),
    ]
