# pylint: disable=C0103
# Generated by Django 4.2.3 on 2023-08-01 02:04
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("empresas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pretensao_salario",
                    models.CharField(
                        choices=[
                            ("Até 1000", "Até 1000"),
                            ("De 1000 a 2000", "De 1000 a 2000"),
                            ("De 2000 a 3000", "De 2000 a 3000"),
                            ("Acima de 3000", "Acima de 3000"),
                        ],
                        default="Até 1000",
                        max_length=50,
                    ),
                ),
                (
                    "experiencia",
                    models.CharField(
                        choices=[
                            ("Até 1 ano", "Até 1 ano"),
                            ("De 1 ano a 2 anos", "De 1 ano a 2 anos"),
                            ("De 2 anos a 3 anos", "De 2 anos a 3 anos"),
                            ("Acima de 3 anos", "Acima de 3 anos"),
                        ],
                        default="Até 1 ano",
                        max_length=50,
                    ),
                ),
                (
                    "ultima_escolaridade",
                    models.CharField(
                        choices=[
                            ("Ensino fundamental", "Ensino fundamental"),
                            ("Ensino médio", "Ensino médio"),
                            ("Tecnólogo", "Tecnólogo"),
                            ("Ensino Superior", "Ensino Superior"),
                            ("Pós / MBA / Mestrado", "Pós / MBA / Mestrado"),
                            ("Doutorado", "Doutorado"),
                        ],
                        default="Ensino fundamental",
                        max_length=50,
                    ),
                ),
                ("pontuacao", models.IntegerField(default=0)),
                (
                    "candidato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vaga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="empresas.vagas"
                    ),
                ),
            ],
        ),
    ]
